### ISSUE TITLE
Relationship does not conform to definition

### ISSUE THREAD

**Issue by raul-nugis** [pyArchimate/pyArchimate#12]
**from pyArchimate import Relationship
a_relationship = Relationship(rel_type="Association", parent=model)**

ValueError                                Traceback (most recent call last)
[<ipython-input-91-92ea51ae28e6>](https://localhost:8080/#) in <cell line: 2>()
      1 from pyArchimate import Relationship
----> 2 a_relationship = Relationship(rel_type="Association", parent=model)

[/usr/local/lib/python3.10/dist-packages/pyArchimate/pyArchimate.py](https://localhost:8080/#) in __init__(self, rel_type, source, target, uuid, name, access_type, influence_strength, desc, is_directed, parent)
    841             self._source = source
    842         elif not isinstance(source, Element) and not isinstance(source, Relationship):
--> 843             raise ValueError("'source' argument is not an instance of 'Element or Relationship' class.")
    844         else:
    845             self._source = source.uuid

ValueError: 'source' argument is not an instance of 'Element or Relationship' class.

**Also, it is not possible to instantiate based on
Class definition:**

class Relationship(builtins.object)
 |  Relationship(rel_type='', source=None, target=None, uuid=None, name=None, access_type=None, influence_strength=None, desc=None, is_directed=None, parent=None)

**Does not work:**

**a_relationship = Relationship(rel_type='Association', 
                              source=None, 
                              target=None, 
                              uuid=None, 
                              name=None, 
                              access_type=None, 
                              influence_strength=None, 
                              desc=None, 
                              is_directed=None, 
                              parent=None)**

**Comment by xmayeur** [comment]
Hello Raul,

I have not written the classes to be used without argument at instantiation, therefore the errors
Furthermore, use the methods of the model class to add or modify elements, relationships, nodes, connections. It is much more easier, and there is no need to instantiate manually other classes..


Do something like this:

```
    from src.pyArchimate.logger import *
    from src.pyArchimate.pyArchimate import *


     # create model with a name
    m = Model('My Model')
    # add a description
    m.desc = 'This is my new Model'
    m.prop('version', '1.0')
    m.prop('author', 'Raul Nugis')

    # add elements and relationships
    e = m.add(concept_type=ArchiType.ApplicationCollaboration, name="App 1", desc="An Application 1")
    e.prop('Architect', 'Harry Potter')
    e2 = m.add(name='App 2', concept_type=ArchiType.ApplicationCollaboration)
    rel = m.add_relationship(source=e, target=e2, rel_type=ArchiType.Flow, name='Flow to')

```


Look at test_pyArchimate.py for some examples and look at the documentation https://pyarchimate.readthedocs.io
I will try to develop more examples and better indicates in the doc the mandatory parameters.

Good luck and do not hesitate to contact me for further info.

Xavier

**Comment by xmayeur** [comment]
Also look at the following code: this creates a model, a view, two nodes and a connection between them. The related elements and relationships are automatically created.

`
import pyArchimate as pa
from pyArchimate.writers.archimateWriter import archimate_writer


def main():
    # create a new model
    m = pa.Model("My Model")
    m.prop("author", "X. Mayeur")
    m.prop("version", "1.0.0")

    # Add a view
    v = m.add(concept_type=pa.ArchiType.View, name="view 1")

    # Add an node in the view and create the related element
    n_app_srv = v.get_or_create_node(
        "Application Service",
        pa.ArchiType.ApplicationService,
        20,
        20,
        create_elem=True,
        create_node=True,
    )
    # Add another one
    n_app_comp = v.get_or_create_node(
        "Application Component",
        pa.ArchiType.ApplicationComponent,
        x=200,
        y=20,
        create_elem=True,
        create_node=True,
    )
    # and create a relation between both
    v.get_or_create_connection(
        rel_type=pa.ArchiType.Serving,
        source=n_app_comp,
        target=n_app_srv,
        create_conn=True,
        name="Serves",
    )

    m.write("my_model.archimate", writer=archimate_writer)


if __name__ == "__main__":
    main()

`
